/// Trait that defines common currency metadata
pub trait Currency {
    /// ISO 4217 currency alphabethical code (e.g., "USD", "EUR")
    const CODE: &'static str;

    /// Currency symbol (e.g., "$", "€")
    const SYMBOL: &'static str;

    /// Full currency name (e.g., "US Dollar", "Euro")
    const NAME: &'static str;

    /// ISO 4217 numeric code
    const NUMERIC: u16;

    /// Number of decimal places (minor units)
    const MINOR_UNIT: u16;

    /// Symbol of currency's minor unit
    const MINOR_UNIT_SYMBOL: &'static str;

    /// thousand separator
    const THOUSAND_SEPARATOR: &'static str;

    /// decimal separator
    const DECIMAL_SEPARATOR: &'static str;
}

// Currencies generated by build.rs
include!(concat!(env!("OUT_DIR"), "/currencies.rs"));
